# Generated by Django 5.0.4 on 2024-04-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
